services:
  mysql8-container:
    image: mysql:8.2.0
    container_name: mysql8-container
    restart: always
    ports: 
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD: Mysql123@
    - MYSQL_DATABASE: Mysql123@

  networks:
    mydatabases: 
    #docker-compose -f ./deployment.yml up -d
    